#*****************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# project..tcl: Tcl script for re-creating project 'QBert-KR260'
#
# Generated by Vivado on Wed Jul 05 12:31:41 +0200 2023
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project..tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/../sources/8088/biu_min.v"]"\
 "[file normalize "$origin_dir/../sources/dpram.v"]"\
 "[file normalize "$origin_dir/../sources/8088/eu_rom.v"]"\
 "[file normalize "$origin_dir/../sources/8088/i8088.v"]"\
 "[file normalize "$origin_dir/../sources/8088/mcl86_eu_core.v"]"\
 "[file normalize "$origin_dir/../sources/ram.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74138.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74139.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74157.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74161.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74166.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74189.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74244.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74245.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74283.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74298.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74367.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74374.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x74379.v"]"\
 "[file normalize "$origin_dir/../sources/7400/x7474.v"]"\
 "[file normalize "$origin_dir/../sources/mylstar_board.v"]"\
 "[file normalize "$origin_dir/../sources/6502/ALU.v"]"\
 "[file normalize "$origin_dir/../sources/6502/cpu6502.v"]"\
 "[file normalize "$origin_dir/../sources/riot.v"]"\
 "[file normalize "$origin_dir/../sources/sc01.v"]"\
 "[file normalize "$origin_dir/../sources/ma216_board.v"]"\
 "[file normalize "$origin_dir/../sources/subclock.v"]"\
 "[file normalize "$origin_dir/../sources/pmod_audio.v"]"\
 "[file normalize "$origin_dir/../sources/8088/biu_max.v"]"\
 "[file normalize "$origin_dir/../sources/pll.v"]"\
 "[file normalize "$origin_dir/../sources/pll/pll_0002.v"]"\
 "[file normalize "$origin_dir/../sources/constraints/top.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "QBert-KR260"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../../"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xck26-sfvc784-2LV-c

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
#set_property -name "board_part_repo_paths" -value "[file normalize "$origin_dir/../../../../../../AppData/Roaming/Xilinx/Vivado/2022.1/xhub/board_store/xilinx_board_store"] [file normalize "$origin_dir/../../../../kria-vitis-platforms/kr260/platforms/vivado/board_files/kr260_carrier/1.0"] [file normalize "$origin_dir/../../../../kria-vitis-platforms/kr260/platforms/vivado/board_files/kr260_som/1.0"]" -objects $obj
set_property -name "board_part" -value "xilinx.com:kr260_som:part0:1.0" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "kr260_som" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "$origin_dir/../sources/8088/biu_min.v"]\
 [file normalize "$origin_dir/../sources/dpram.v"]\
 [file normalize "$origin_dir/../sources/8088/eu_rom.v"]\
 [file normalize "$origin_dir/../sources/8088/i8088.v"]\
 [file normalize "$origin_dir/../sources/8088/mcl86_eu_core.v"]\
 [file normalize "$origin_dir/../sources/ram.v"]\
 [file normalize "$origin_dir/../sources/7400/x74138.v"]\
 [file normalize "$origin_dir/../sources/7400/x74139.v"]\
 [file normalize "$origin_dir/../sources/7400/x74157.v"]\
 [file normalize "$origin_dir/../sources/7400/x74161.v"]\
 [file normalize "$origin_dir/../sources/7400/x74166.v"]\
 [file normalize "$origin_dir/../sources/7400/x74189.v"]\
 [file normalize "$origin_dir/../sources/7400/x74244.v"]\
 [file normalize "$origin_dir/../sources/7400/x74245.v"]\
 [file normalize "$origin_dir/../sources/7400/x74283.v"]\
 [file normalize "$origin_dir/../sources/7400/x74298.v"]\
 [file normalize "$origin_dir/../sources/7400/x74367.v"]\
 [file normalize "$origin_dir/../sources/7400/x74374.v"]\
 [file normalize "$origin_dir/../sources/7400/x74379.v"]\
 [file normalize "$origin_dir/../sources/7400/x7474.v"]\
 [file normalize "$origin_dir/../sources/mylstar_board.v"]\
 [file normalize "$origin_dir/../sources/6502/ALU.v"]\
 [file normalize "$origin_dir/../sources/6502/cpu6502.v"]\
 [file normalize "$origin_dir/../sources/riot.v"]\
 [file normalize "$origin_dir/../sources/sc01.v"]\
 [file normalize "$origin_dir/../sources/ma216_board.v"]\
 [file normalize "$origin_dir/../sources/subclock.v" ]\
 [file normalize "$origin_dir/../sources/pmod_audio.v"]\
 [file normalize "$origin_dir/../sources/8088/biu_max.v"]\
 [file normalize "$origin_dir/../sources/pll.v"]\
 [file normalize "$origin_dir/../sources/pll/pll_0002.v"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "design_1_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize $origin_dir/../sources/constraints/top.xdc]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "constraints/top.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "mylstar_board" -objects $obj
set_property -name "top_file" -value "$origin_dir/../sources/mylstar_board.v" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
if { [get_files biu_min.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/8088/biu_min.v
}
if { [get_files dpram.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/dpram.v
}
if { [get_files eu_rom.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/8088/eu_rom.v
}
if { [get_files i8088.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/8088/i8088.v
}
if { [get_files mcl86_eu_core.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/8088/mcl86_eu_core.v
}
if { [get_files ram.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/ram.v
}
if { [get_files x74138.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74138.v
}
if { [get_files x74139.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74139.v
}
if { [get_files x74157.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74157.v
}
if { [get_files x74161.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74161.v
}
if { [get_files x74166.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74166.v
}
if { [get_files x74189.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74189.v
}
if { [get_files x74244.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74244.v
}
if { [get_files x74245.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74245.v
}
if { [get_files x74283.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74283.v
}
if { [get_files x74298.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74298.v
}
if { [get_files x74367.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74367.v
}
if { [get_files x74374.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74374.v
}
if { [get_files x74379.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74379.v
}
if { [get_files x7474.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x7474.v
}
if { [get_files mylstar_board.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/mylstar_board.v
}
if { [get_files ALU.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/6502/ALU.v
}
if { [get_files cpu6502.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/6502/cpu6502.v
}
if { [get_files dpram.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/dpram.v
}
if { [get_files riot.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/riot.v
}
if { [get_files sc01.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/sc01.v
}
if { [get_files x74138.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/7400/x74138.v
}
if { [get_files ma216_board.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/ma216_board.v
}
if { [get_files subclock.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/subclock.v
}
if { [get_files pmod_audio.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../sources/pmod_audio.v
}


# Proc to create BD design_1
proc cr_bd_design_1 { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# ma216_board, mylstar_board, pmod_audio, subclock



  # CHANGE DESIGN NAME HERE
  set design_name design_1

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:xlconcat:2.1\
  xilinx.com:ip:xlconstant:1.1\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  ma216_board\
  mylstar_board\
  pmod_audio\
  subclock\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set AUDIO_LEFT [ create_bd_port -dir O AUDIO_LEFT ]
  set AUDIO_RIGHT [ create_bd_port -dir O AUDIO_RIGHT ]
  set BLUE [ create_bd_port -dir O -from 3 -to 0 BLUE ]
  set BUTTONS [ create_bd_port -dir I -from 7 -to 0 BUTTONS ]
  set CLK_IN_gem [ create_bd_port -dir I -type clk -freq_hz 25000000 CLK_IN_gem ]
  set GREEN [ create_bd_port -dir O -from 3 -to 0 GREEN ]
  set HSYNC [ create_bd_port -dir O HSYNC ]
  set RED [ create_bd_port -dir O -from 3 -to 0 RED ]
  set RESET [ create_bd_port -dir I RESET ]
  set VSYNC [ create_bd_port -dir O VSYNC ]

  # Create instance: clk_wiz_0, and set properties
  set clk_wiz_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_0 ]
  set_property -dict [ list \
   CONFIG.CLKIN1_JITTER_PS {400.0} \
   CONFIG.CLKOUT1_JITTER {207.962} \
   CONFIG.CLKOUT1_PHASE_ERROR {222.305} \
   CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {50.000} \
   CONFIG.CLKOUT1_USED {true} \
   CONFIG.CLKOUT2_JITTER {214.025} \
   CONFIG.CLKOUT2_PHASE_ERROR {222.305} \
   CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {40.000} \
   CONFIG.CLKOUT2_USED {true} \
   CONFIG.CLKOUT3_JITTER {233.133} \
   CONFIG.CLKOUT3_PHASE_ERROR {222.305} \
   CONFIG.CLKOUT3_REQUESTED_OUT_FREQ {25.000} \
   CONFIG.CLKOUT3_USED {true} \
   CONFIG.CLKOUT4_JITTER {190.517} \
   CONFIG.CLKOUT4_PHASE_ERROR {222.305} \
   CONFIG.CLKOUT4_USED {true} \
   CONFIG.CLK_OUT1_PORT {clk_50} \
   CONFIG.CLK_OUT2_PORT {clk_40} \
   CONFIG.CLK_OUT3_PORT {clk_25} \
   CONFIG.CLK_OUT4_PORT {clk_100} \
   CONFIG.MMCM_CLKFBOUT_MULT_F {48.000} \
   CONFIG.MMCM_CLKIN1_PERIOD {40.000} \
   CONFIG.MMCM_CLKIN2_PERIOD {10.0} \
   CONFIG.MMCM_CLKOUT0_DIVIDE_F {24.000} \
   CONFIG.MMCM_CLKOUT1_DIVIDE {30} \
   CONFIG.MMCM_CLKOUT2_DIVIDE {48} \
   CONFIG.MMCM_CLKOUT3_DIVIDE {12} \
   CONFIG.NUM_OUT_CLKS {4} \
   CONFIG.PRIM_IN_FREQ {25.000} \
   CONFIG.USE_LOCKED {false} \
   CONFIG.USE_RESET {false} \
 ] $clk_wiz_0

  # Create instance: ma216_board_0, and set properties
  set block_name ma216_board
  set block_cell_name ma216_board_0
  if { [catch {set ma216_board_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $ma216_board_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: mylstar_board_0, and set properties
  set block_name mylstar_board
  set block_cell_name mylstar_board_0
  if { [catch {set mylstar_board_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $mylstar_board_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: pmod_audio_0, and set properties
  set block_name pmod_audio
  set block_cell_name pmod_audio_0
  if { [catch {set pmod_audio_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $pmod_audio_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: subclock_0, and set properties
  set block_name subclock
  set block_cell_name subclock_0
  if { [catch {set subclock_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $subclock_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: xlconcat_0, and set properties
  set xlconcat_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat:2.1 xlconcat_0 ]
  set_property -dict [ list \
   CONFIG.IN0_WIDTH {8} \
   CONFIG.IN1_WIDTH {8} \
 ] $xlconcat_0

  # Create instance: xlconstant_0, and set properties
  set xlconstant_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 xlconstant_0 ]
  set_property -dict [ list \
   CONFIG.CONST_VAL {0} \
   CONFIG.CONST_WIDTH {8} \
 ] $xlconstant_0

  # Create port connections
  connect_bd_net -net BUTTONS_1 [get_bd_ports BUTTONS] [get_bd_pins mylstar_board_0/dip_switch]
  connect_bd_net -net CLK_IN_gem_1 [get_bd_ports CLK_IN_gem] [get_bd_pins clk_wiz_0/clk_in1]
  connect_bd_net -net RESET_1 [get_bd_ports RESET] [get_bd_pins ma216_board_0/reset] [get_bd_pins mylstar_board_0/reset]
  connect_bd_net -net clk_wiz_0_clk_40 [get_bd_pins clk_wiz_0/clk_40] [get_bd_pins subclock_0/clk_40]
  connect_bd_net -net clk_wiz_0_clk_50 [get_bd_pins clk_wiz_0/clk_50] [get_bd_pins ma216_board_0/clk_sys] [get_bd_pins mylstar_board_0/clk_sys] [get_bd_pins subclock_0/clk_sys]
  connect_bd_net -net clk_wiz_0_clk_100 [get_bd_pins clk_wiz_0/clk_100] [get_bd_pins mylstar_board_0/CPU_CORE_CLK]
  connect_bd_net -net ma216_board_0_audio [get_bd_pins ma216_board_0/audio] [get_bd_pins xlconcat_0/In0]
  connect_bd_net -net mylstar_board_0_HSync [get_bd_ports HSYNC] [get_bd_pins mylstar_board_0/HSync]
  connect_bd_net -net mylstar_board_0_VSync [get_bd_ports VSYNC] [get_bd_pins mylstar_board_0/VSync]
  connect_bd_net -net mylstar_board_0_blue [get_bd_ports BLUE] [get_bd_pins mylstar_board_0/blue]
  connect_bd_net -net mylstar_board_0_green [get_bd_ports GREEN] [get_bd_pins mylstar_board_0/green]
  connect_bd_net -net mylstar_board_0_red [get_bd_ports RED] [get_bd_pins mylstar_board_0/red]
  connect_bd_net -net pmod_audio_0_output_pmod [get_bd_ports AUDIO_LEFT] [get_bd_pins pmod_audio_0/output_pmod]
  connect_bd_net -net pmod_audio_0_output_pmod2 [get_bd_ports AUDIO_RIGHT] [get_bd_pins pmod_audio_0/output_pmod2]
  connect_bd_net -net subclock_0_clk_5 [get_bd_pins mylstar_board_0/CLK5] [get_bd_pins subclock_0/clk_5]
  connect_bd_net -net subclock_0_clk_10 [get_bd_pins mylstar_board_0/CLK] [get_bd_pins subclock_0/clk_10]
  connect_bd_net -net subclock_0_cpu_clk [get_bd_pins mylstar_board_0/CPU_CLK] [get_bd_pins subclock_0/cpu_clk]
  connect_bd_net -net subclock_0_sound_clk [get_bd_pins ma216_board_0/clk] [get_bd_pins pmod_audio_0/clk] [get_bd_pins subclock_0/sound_clk]
  connect_bd_net -net xlconcat_0_dout [get_bd_pins pmod_audio_0/sample] [get_bd_pins xlconcat_0/dout]
  connect_bd_net -net xlconstant_0_dout [get_bd_pins xlconcat_0/In1] [get_bd_pins xlconstant_0/dout]

  # Create address segments

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.672",
   "Default View_TopLeft":"-229,0",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.0r6  2020-01-29 bk=1.5227 VDI=41 GEI=36 GUI=JA:10.0 non-TLS
#  -string -flagsOSRD
preplace port port-id_CLK_IN_gem -pg 1 -lvl 0 -x 0 -y 420 -defaultsOSRD
preplace port port-id_RESET -pg 1 -lvl 0 -x 0 -y 100 -defaultsOSRD
preplace port port-id_HSYNC -pg 1 -lvl 6 -x 1310 -y 470 -defaultsOSRD
preplace port port-id_VSYNC -pg 1 -lvl 6 -x 1310 -y 510 -defaultsOSRD
preplace port port-id_AUDIO_LEFT -pg 1 -lvl 6 -x 1310 -y 250 -defaultsOSRD
preplace port port-id_AUDIO_RIGHT -pg 1 -lvl 6 -x 1310 -y 270 -defaultsOSRD
preplace portBus RED -pg 1 -lvl 6 -x 1310 -y 530 -defaultsOSRD
preplace portBus GREEN -pg 1 -lvl 6 -x 1310 -y 550 -defaultsOSRD
preplace portBus BLUE -pg 1 -lvl 6 -x 1310 -y 570 -defaultsOSRD
preplace portBus BUTTONS -pg 1 -lvl 0 -x 0 -y 570 -defaultsOSRD
preplace inst clk_wiz_0 -pg 1 -lvl 1 -x 110 -y 420 -defaultsOSRD
preplace inst ma216_board_0 -pg 1 -lvl 3 -x 610 -y 120 -defaultsOSRD
preplace inst subclock_0 -pg 1 -lvl 2 -x 310 -y 400 -defaultsOSRD
preplace inst mylstar_board_0 -pg 1 -lvl 5 -x 1130 -y 540 -defaultsOSRD
preplace inst pmod_audio_0 -pg 1 -lvl 5 -x 1130 -y 260 -defaultsOSRD
preplace inst xlconcat_0 -pg 1 -lvl 4 -x 860 -y 320 -defaultsOSRD
preplace inst xlconstant_0 -pg 1 -lvl 3 -x 610 -y 330 -defaultsOSRD
preplace netloc CLK_IN_gem_1 1 0 1 NJ 420
preplace netloc clk_wiz_0_clk_50 1 1 4 200 310 460 390 NJ 390 NJ
preplace netloc clk_wiz_0_clk_40 1 1 1 N 410
preplace netloc subclock_0_cpu_clk 1 2 3 420 470 NJ 470 NJ
preplace netloc subclock_0_clk_5 1 2 3 430 450 NJ 450 NJ
preplace netloc subclock_0_sound_clk 1 2 3 440 250 NJ 250 NJ
preplace netloc clk_wiz_0_clk_100 1 1 4 200 490 NJ 490 NJ 490 NJ
preplace netloc subclock_0_clk_10 1 2 3 450 430 NJ 430 NJ
preplace netloc RESET_1 1 0 5 NJ 100 NJ 100 450 240 NJ 240 960
preplace netloc mylstar_board_0_red 1 5 1 NJ 530
preplace netloc mylstar_board_0_green 1 5 1 NJ 550
preplace netloc mylstar_board_0_blue 1 5 1 NJ 570
preplace netloc mylstar_board_0_HSync 1 5 1 NJ 470
preplace netloc mylstar_board_0_VSync 1 5 1 NJ 510
preplace netloc ma216_board_0_audio 1 3 1 760 120n
preplace netloc xlconstant_0_dout 1 3 1 NJ 330
preplace netloc xlconcat_0_dout 1 4 1 970 270n
preplace netloc pmod_audio_0_output_pmod 1 5 1 NJ 250
preplace netloc pmod_audio_0_output_pmod2 1 5 1 NJ 270
preplace netloc BUTTONS_1 1 0 5 NJ 570 NJ 570 NJ 570 NJ 570 NJ
levelinfo -pg 1 0 110 310 610 860 1130 1310
pagesize -pg 1 -db -bbox -sgen -150 0 1460 750
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_1()
cr_bd_design_1 ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_1.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_1.bd ] 

#call make_wrapper to create wrapper files

set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse design_1.bd] -top]
add_files -norecurse -fileset sources_1 $wrapper_path
